package org.minimarket.client.salesReport;

import javafx.collections.FXCollections;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import org.minimarket.catalogue.SaleRecord;
import org.minimarket.storageAccess.SalesFileManager;

import java.util.List;

/**
 * The SalesReportController is responsible for displaying a table of all
 * recorded sales in the system. It loads the sales log from storage, displays
 * each sale in a JavaFX TableView, and calculates the total revenue.
 *
 * This controller is part of the GUI component responsible for reporting
 * and analytics in the Mini Market application.
 */
public class SalesReportController {

    /** Table that displays all sale records */
    @FXML private TableView<SaleRecord> salesTable;

    /** Column showing the product name for each sale */
    @FXML private TableColumn<SaleRecord, String> colProduct;

    /** Column showing the quantity sold */
    @FXML private TableColumn<SaleRecord, Integer> colQty;

    /** Column showing the subtotal (£) generated by the sale */
    @FXML private TableColumn<SaleRecord, Double> colSubtotal;

    /** Label showing the total revenue from all recorded sales */
    @FXML private Label lblTotal;

    /** Handles loading and saving sales data to the CSV files */
    private final SalesFileManager salesFileManager = new SalesFileManager();

    /**
     * Called automatically when the FXML view is loaded.
     * Sets up the table columns and loads all stored sales records.
     */
    @FXML
    public void initialize() {
        // Ensure that all FXML elements were injected properly
        assert salesTable != null : "fx:id=\"salesTable\" was not injected.";
        assert colProduct != null : "fx:id=\"colProduct\" was not injected.";
        assert colQty != null : "fx:id=\"colQty\" was not injected.";
        assert colSubtotal != null : "fx:id=\"colSubtotal\" was not injected.";

        // Bind table columns to SaleRecord fields
        colProduct.setCellValueFactory(new PropertyValueFactory<>("productName"));
        colQty.setCellValueFactory(new PropertyValueFactory<>("quantity"));
        colSubtotal.setCellValueFactory(new PropertyValueFactory<>("subtotal"));

        // Load existing sales into the table
        loadSalesData();
    }

    /**
     * Loads sales data from the SalesFileManager and updates both the
     * TableView and the total sales label.
     */
    private void loadSalesData() {
        // Retrieve all sale records from the CSV file
        List<SaleRecord> records = salesFileManager.loadSaleRecords();

        // Display them in the table
        salesTable.setItems(FXCollections.observableArrayList(records));

        // Calculate and display the total sales revenue
        if (lblTotal != null) {
            double total = records.stream()
                    .mapToDouble(SaleRecord::getSubtotal)
                    .sum();
            lblTotal.setText(String.format("£%.2f", total));
        }
    }
}

