package org.minimarket.client.salesReport;

/**
 * SalesReportModel represents a single row of data shown in the Sales Report table.
 * It contains the product name, the quantity sold, and the subtotal generated.
 *
 * Although the application already uses SaleRecord internally, this model class
 * exists to provide a clean separation between the data stored in the system
 * and the way it is presented in the Sales Report view.
 *
 * This class follows the "Model" part of MVC specifically for reporting.
 */
public class SalesReportModel {

    /** Name of the product that was sold */
    private String productName;

    /** Quantity of the product that was purchased */
    private int quantity;

    /** Revenue generated from this sale (quantity × price) */
    private double subtotal;

    /**
     * Creates a sales report entry with the required fields.
     * name of the sold product
     *  how many units were sold
     *   total revenue for this product
     */
    public SalesReportModel(String productName, int quantity, double subtotal) {
        this.productName = productName;
        this.quantity = quantity;
        this.subtotal = subtotal;
    }

    /**
     * the name of the sold product
     */
    public String getProductName() {
        return productName;
    }

    /**
     *  how many units of the product were sold
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     *  the total revenue generated by this sale entry
     */
    public double getSubtotal() {
        return subtotal;
    }
}
